### ISSUE TITLE
current working directory not in `sys.path` when calling `flake8`

### ISSUE THREAD

**Issue by ioga** [atollk/flake8-import-restrictions#13]
Hey there,

First of all, great work, thanks a ton of making this plugin.

We're using `flake8-import-restrictions==1.1.1` because we still need to support python 3.7 and an older flake8 version.

Let's say we have `somepackage/` directory within the current directory, and several python files in it doing `from somepackage import ...`. We were seeing false `I2041` errors with the plugin, and after some debugging we've tracked it down to the `imports_submodule` trying to import the code and failing because the current directory containing the code was not in `sys.path`.

What does not work:
- Running `flake8`, which is `flake8`'s default recommendation.

What works:
- Running `python -m flake8`
- Running `PYTHONPATH="." flake8`
- explicitly `pip install`-ing `somepackage` so it's importable by default

Per [sys.path docs](https://docs.python.org/3/library/sys.html#sys.path), `python -m flake8` would prepend the current working directory, while `flake8` does not do it, so it breaks. `PYTHONPATH` and package install hacks solve the imports problem similarly. Vanilla flake8 w/o the plugin is unaffected because I assume it does not try to actually do the imports.

I am curious if you've encountered this problem, and if so, how did you work around it?

Thanks!

**Comment by atollk** [comment]
Hey. Thanks for the report. I can't say that I remember encountering this issue but maybe our flake8 version was even older than yours :)

Would you able to create a test case which reproduces this error? Or an entire including the fix, if you want to.
