### ISSUE TITLE
flake8 6.* support

### ISSUE THREAD

**Issue by svntmr** [atollk/flake8-import-restrictions#16]
Hi @atollk 👋 

Thanks for this great plugin, it helps me to enforce imports to follow Goggle Python Style Guide  

Just a question: do you have a plan to support `6.*` versions of `flake8`?

**Comment by atollk** [comment]
Hey, thanks for the praise. 
I haven't used Python myself recently so I don't know what changed with flake8 v6, or rather, how flake8-import-restrictions doesn't already support it yet.

**Comment by svntmr** [comment]
thanks for the fast response!
I though it might be a reason for problems in #17, but we'll see
closing this one
